import React, { useRef, useEffect, useState } from 'react';
import './App.css';
import PieChart from "./PieChart.jsx";
import Stepper from "./Stepper.jsx";
import EntryDiv from "./EntryDiv.jsx";

function Header() {
  return(
    <header>
        <h1>
          Slice the Pie
        </h1>
        <p>
          Say you got to run the University. How much would you allocate to different sectors? Learn about your funding sources, with a guessing game.
        </p>
        <p>
          You make your choices by inputting percentages of each section of a pie chart. See how well your choices match the ones the real Provost made.
        </p>
    </header>
  )
}


/* App */
function App() {

  let realRev = [ 
    { name: "Medical Center", value: 45, color: '#f0bf00' },
    { name: "State of California", value: 8, color: '#f6e50e' },
    { name: "Tuition", value: 11, color: '#fff688' }, 
    { name: "Student Fees", value: 4, color: '#5f63ec' },
    { name: "Research Grants and Contracts", value: 13, color: '#71a8ff' }, 
    { name: "Non-educational Services", value: 11, color:'#58C9FB' },
    { name: "Gifts, Endowments, Interest, etc.", value: 7, color: '#0f7ab4' },
    { name: "Pell Grants", value: 1, color: '#d4e4ff' }
  ]; 

   const [revData, setRevData] = useState([
    { name: "Medical Center", value: 0, color: '#f0bf00', caption: "A large, not-for-profit regional medical center, including multiple hospitals, labs and clinics. Income comes from patients, medical insurance companies, and government programs like medicare." },
    { name: "State of California", value: 0, color: '#f6e50e', caption:  "General funds given by the taxpayers of California, appropriated annualy by the state legislature. General funds are not dedicated to specific services." },
    { name: "Tuition", value: 0, color: '#fff688', caption: "Students pay tuition to attend the University. Non-California residents pay about twice as much as residents.  Tuition is also general funds." }, 
    { name: "Student Fees", value: 0, color: '#5f63ec', caption: "Fees are dedicated to specific services, such as athletic facilities, bus service (UNITRANS), student organizations, the CoHo and Student Community Center, etc." },
    { name: "Research Grants and Contracts", value: 0, color: '#71a8ff', caption: "Government and industry funds given to faculty and graduate students to perform research projects. These include up to 50% overhead in addition to the cost of the research." }, 
    { name: "Non-educational Services", value: 0, color:'#58C9FB', caption: "Services other than education that people pay for, like dorms, dining, parking, etc.  At UC Davis, this also includes almost $500M of revenue generated by medical school faculty, or 8%, making this category look really big." },
    { name: "Gifts, Endowments, Interest, etc.", value: 0, color: '#0f7ab4', caption: "Endowments are past gifts that were invested to provide income; interest is earned on other savings. The Museum is the direct result of a $10M gift from Jan Shrem and Maria Manetti Shrem." },
    { name: "Pell Grants", value: 0, color: '#d4e4ff', caption: "Federal grants for tuition and living expenses for low-income students. Percentage of students with Pell grants is a good way to measure who a University serves; at UCD, it's 34%; at Cal Tech it's 14%; at Sac State it's 71%." }
  ]);

   const [realExp, setRealExp] = useState([ 
      { name: "Medical Center", value: 43, color: '#f0bf00'}, 
      { name: "Teaching and Teaching Support", value: 23, color: '#f6e50e' }, 
      { name: "Research", value: 11, color: '#fff688' }, 
      { name: "Student Services and Financial Aid", value: 8, color: '#5f63ec' }, 
      { name: "Operations and Maintenance", value: 2, color: '#71a8ff' }, 
      { name: "Administration", value: 3, color:'#58C9FB' }, 
      { name: "Non-Educational Services", value: 2, color: '#0f7ab4' }, 
      { name: "Public Service", value: 2, color: '#d4e4ff' }, 
      { name: "Depreciation, Interest, etc.", value: 6, color: 'white' } 
    ]); 

  const [expData, setExpData] = useState([
      { name: "Medical Center", value: 0, color: '#f0bf00', caption: "The cost of providing care at the Medical Center is roughly what we get paid to provide it."}, 
      { name: "Teaching and Teaching Support", value: 0, color: '#f6e50e', caption: "Professors, advisors, deans, the library, the computer labs, etc, including Medical School faculty salaries." }, 
      { name: "Research", value: 0, color: '#fff688', caption: "The costs of doing the research, mostly researcher salaries." }, 
      { name: "Student Services and Financial Aid", value: 0, color: '#5f63ec',  caption: "Student Health, things covered by fees, Admissions, and also financial aid from the general funds, which is about $100M or 1.5%." }, 
      { name: "Operations and Maintenance", value: 0, color: '#71a8ff', caption: "Upkeep of the grounds and building, and utilities, which are less than 1%." }, 
      { name: "Administration", value: 0, color:'#58C9FB', caption: "Provost and Chancellor's offices, raising money, accounting, personnel, legal, making budgets." }, 
      { name: "Non-Educational Services", value: 0, color: '#0f7ab4', caption: "The costs of providing dorms, dining, parking, etc." }, 
      { name: "Public Service", value: 0, color: '#d4e4ff', caption: "Mostly the cooperative extension, which provides agricultural services to farmers, ranchers, winemakers, etc.  Part of our mission as a land grant university." }, 
      { name: "Depreciation, Interest, etc.", value: 0, color: 'white',  caption: "Depreciation is the loss of value of buildings and equipment as they wear out. Mostly unavoidable financial losses." } 
  ]);

  function updateRevPie (name, value) {
    let revDataCopy = [...revData];
    for(let i=0; i < revDataCopy.length; i++){
      if(name === revDataCopy[i].name){
        revDataCopy[i].value = 1*value;
      }
    }
    setRevData(revDataCopy);    
  }

  function updateExpPie (name, value) {
    let expDataCopy = [...expData];
    for(let i=0; i < expDataCopy.length; i++){
      if(name === expDataCopy[i].name){
        expDataCopy[i].value = 1*value;
      }
    }
    setExpData(expDataCopy);
  }


  const [page, setPage] = useState("Revenues");
  

  {switch(page) {
    case "Revenues":
      return (
        <main>
          <Header />

          <Stepper step="Revenues"/>

          <h2>UC Davis Revenues</h2>
          <div className='pie-chart'>
            <PieChart name={"revInput"} data={revData} />
          </div>

          <EntryDiv sc={updateRevPie} data={revData} />

          <button className="white-btn" onClick={()=>{
            setPage("Expenses");
            setExpData([...expData]);
            }}> Next </button>
        </main>
      )

    case "Expenses":
      return(
        <main>
          <Header />

          <Stepper step="Expenses"/>

          <h2>UC Davis Expenditures</h2>
          <h3 />
          <div className='pie-chart'>
            <PieChart name={"expInput"} data={expData} />
          </div>       
          
          <EntryDiv sc={updateExpPie} data={expData} />

          <button className="blue-btn" onClick={()=>{
            setPage("CompareRev");
          }}> Compare </button>

          <button className="grey-btn" onClick={()=>{
          setPage("Revenues");
    
          }}> Previous </button>
        </main>
      )

    case "CompareRev":
      return (
        <main>
          <Header />

          <Stepper step="Compare" />

          <h1>RESULTS</h1>

          <h2>Your Revenue Guess</h2>
          <h3 />
            <div className='pie-chart'>
              <PieChart name={"revData"} data={revData} />
            </div>
            
          <h2>Actual Revenue</h2>
            <div className='pie-chart' id="rev">
              <PieChart name={"realRev"} data={realRev} />
            </div>

          <button className="white-btn" onClick={()=>{
          setPage("CompareExp");
          setRealExp([...realExp]);
          }}> Next </button>
        </main>
      )

    case "CompareExp":
      return (
        <main>
          <Header />

          <Stepper step="Compare" />

          <h1>RESULTS</h1>

          <h2>Your Expenses Guess</h2>
          
            <div className='pie-chart'>
              <h4 />
              <PieChart name={"expData"} data={expData} />
            </div>
          <h2>Actual Expenses</h2>
          
            <div className='pie-chart' id="exp">
            <h3 />
              <PieChart name={"realExp"} data={realExp} />
            </div>


          <button className="white-btn" onClick={()=>{
          setPage("Revenues");
          setRevData([
            { name: "Medical Center", value: 0, color: '#f0bf00', caption: "A large, not-for-profit regional medical center, including multiple hospitals, labs and clinics. Income comes from patients, medical insurance companies, and government programs like medicare." },
            { name: "State of California", value: 0, color: '#f6e50e', caption:  "General funds given by the taxpayers of California, appropriated annualy by the state legislature. General funds are not dedicated to specific services." },
            { name: "Tuition", value: 0, color: '#fff688', caption: "Students pay tuition to attend the University. Non-California residents pay about twice as much as residents.  Tuition is also general funds." }, 
            { name: "Student Fees", value: 0, color: '#5f63ec', caption: "Fees are dedicated to specific services, such as athletic facilities, bus service (UNITRANS), student organizations, the CoHo and Student Community Center, etc." },
            { name: "Research Grants and Contracts", value: 0, color: '#71a8ff', caption: "Government and industry funds given to faculty and graduate students to perform research projects. These include up to 50% overhead in addition to the cost of the research." }, 
            { name: "Non-educational Services", value: 0, color:'#58C9FB', caption: "Services other than education that people pay for, like dorms, dining, parking, etc.  At UC Davis, this also includes almost $500M of revenue generated by medical school faculty, or 8%, making this category look really big." },
            { name: "Gifts, Endowments, Interest, etc.", value: 0, color: '#0f7ab4', caption: "Endowments are past gifts that were invested to provide income; interest is earned on other savings. The Museum is the direct result of a $10M gift from Jan Shrem and Maria Manetti Shrem." },
            { name: "Pell Grants", value: 0, color: '#d4e4ff', caption: "Federal grants for tuition and living expenses for low-income students. Percentage of students with Pell grants is a good way to measure who a University serves; at UCD, it's 34%; at Cal Tech it's 14%; at Sac State it's 71%." }
          ]);
          setExpData([
              { name: "Medical Center", value: 0, color: '#f0bf00', caption: "The cost of providing care at the Medical Center is roughly what we get paid to provide it."}, 
              { name: "Teaching and Teaching Support", value: 0, color: '#f6e50e', caption: "Professors, advisors, deans, the library, the computer labs, etc, including Medical School faculty salaries." }, 
              { name: "Research", value: 0, color: '#fff688', caption: "The costs of doing the research, mostly researcher salaries." }, 
              { name: "Student Services and Financial Aid", value: 0, color: '#5f63ec',  caption: "Student Health, things covered by fees, Admissions, and also financial aid from the general funds, which is about $100M or 1.5%." }, 
              { name: "Operations and Maintenance", value: 0, color: '#71a8ff', caption: "Upkeep of the grounds and building, and utilities, which are less than 1%." }, 
              { name: "Administration", value: 0, color:'#58C9FB', caption: "Provost and Chancellor's offices, raising money, accounting, personnel, legal, making budgets." }, 
              { name: "Non-Educational Services", value: 0, color: '#0f7ab4', caption: "The costs of providing dorms, dining, parking, etc." }, 
              { name: "Public Service", value: 0, color: '#d4e4ff', caption: "Mostly the cooperative extension, which provides agricultural services to farmers, ranchers, winemakers, etc.  Part of our mission as a land grant university." }, 
              { name: "Depreciation, Interest, etc.", value: 0, color: 'white',  caption: "Depreciation is the loss of value of buildings and equipment as they wear out. Mostly unavoidable financial losses." } 
          ]);
          }}> Restart </button>
        </main>
      )
  }}

  
}

export default App;